# Generated by Django 5.2.4 on 2025-08-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(db_column='topic', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.postmodel', verbose_name='Пост'),
            preserve_default=False,
        ),
    ]
